import React from "react";

import AdminMenu from './Admin-Menu';
import CitiesCompareBarChart from './charts/CitiesCompareBarChart'
import CitiesLineChart from './charts/CitiesLineChart'

import "semantic-ui-css/semantic.min.css";

import {
    Grid,
    Header,
    Segment,
} from "semantic-ui-react";
import axios from 'axios';


export default class adminContent extends React.Component {

    constructor(props) {
        super(props);
        this.state = {
            totalSolarCapacity: null,
            solarCapacityPerCapita: null,
            solarCapacityPerSurfaceArea: null,
            solarCapacityAddedIn30Days: null,
            electricityGeneratedBySolarLast30Days: null,
            solarHouseholdAddedLast30Days: null,
            growthOfSolarCapacity: null,
            newInstallationIncentivesVsCost: null
        }
        const fetchDataUrl = "/api/v1/charting/summaryDashboardData";
        axios.get(fetchDataUrl)
            .then((response) => {
                if (response.data.success) {
                    this.setState({
                        totalSolarCapacity: response.data.result.totalSolarCapacity,
                        solarCapacityPerCapita: response.data.result.solarCapacityPerCapita,
                        solarCapacityPerSurfaceArea: response.data.result.solarCapacityPerSurfaceArea,
                        solarCapacityAddedIn30Days: response.data.result.solarCapacityAddedIn30Days,
                        electricityGeneratedBySolarLast30Days: response.data.result.electricityGeneratedBySolarLast30Days,
                        solarHouseholdAddedLast30Days: response.data.result.solarHouseholdAddedLast30Days,
                        growthOfSolarCapacity: response.data.result.growthOfSolarCapacity,
                        newInstallationIncentivesVsCost: response.data.result.newInstallationIncentivesVsCost
                    })
                }
            })
            .catch(function (error) {
                console.log(error);
            })
    }

    render() {
        return (<div style={{ marginLeft: '50px', marginRight: '50px' }}>
                <Grid>
                    <Grid.Column computer={2} only="tablet computer" id="sidebar">
                        <AdminMenu selected={this.props.selected}/>
                    </Grid.Column>

                    <Grid.Column computer={14} floated="right" id="content">
                        <Grid padded>
                            <Grid.Row> <Header dividing size="huge" as="h1">Summary</Header> </Grid.Row>
                            <Grid.Row columns={3}>
                                <Grid.Column>
                                    <Segment className="chart-container">
                                        <div>Total Solar Capacity</div>
                                        <CitiesCompareBarChart data={this.state.totalSolarCapacity} unit="kW"/>
                                    </Segment>
                                </Grid.Column>
                                <Grid.Column>
                                    <Segment className="chart-container">
                                        <div>Solar Capacity per Capita</div>
                                        <CitiesCompareBarChart data={this.state.solarCapacityPerCapita} unit="Watts/person"/>
                                    </Segment>
                                </Grid.Column>
                                <Grid.Column>
                                    <Segment className="chart-container">
                                        <div>Solar Capacity per Surface Area</div>
                                        <CitiesCompareBarChart data={this.state.solarCapacityPerSurfaceArea} unit="kW/mi²"/>
                                    </Segment>
                                </Grid.Column>
                            </Grid.Row>

                            <Grid.Row columns={3}>
                                <Grid.Column>
                                    <Segment className="chart-container">
                                        <div>Solar Capacity Added (last 30 days)</div>
                                        <CitiesCompareBarChart data={this.state.solarCapacityAddedIn30Days} unit="kW"/>
                                    </Segment>
                                </Grid.Column>
                                <Grid.Column>
                                    <Segment className="chart-container">
                                        <div>Actual Electricity Generated by Solar (last 30 days)</div>
                                        <CitiesCompareBarChart data={this.state.electricityGeneratedBySolarLast30Days} unit="kWh"/>
                                    </Segment>
                                </Grid.Column>
                                <Grid.Column>
                                    <Segment className="chart-container">
                                        <div>Number of Solar Household Added (last 30 days)</div>
                                        <CitiesCompareBarChart data={this.state.solarHouseholdAddedLast30Days} unit="Household"/>
                                    </Segment>
                                </Grid.Column>
                            </Grid.Row>

                            <Grid.Row columns={2}>
                                <Grid.Column>
                                    <Segment className="chart-container">
                                        <div>Growth of Solar Capacity</div>
                                        <CitiesLineChart data={this.state.growthOfSolarCapacity} unit='%'/>
                                    </Segment>
                                </Grid.Column>
                                <Grid.Column>
                                    <Segment className="chart-container">
                                        <div>Rebate Incentives vs Average Installation Cost</div>
                                        <CitiesLineChart data={this.state.newInstallationIncentivesVsCost} unit='USD/Project' showLabels={true} extraLineKey='Average Installation Cost'/>
                                    </Segment>
                                </Grid.Column>
                            </Grid.Row>
                        </Grid>
                    </Grid.Column>
                </Grid>
            </div>
        )
    }
}
